Add new character information from v5.2 Phase 1
gridhead/gi-loadouts pull request #223
Opened 2024-11-23 13:24 UTC by sdglitched

Add new character information from v5.2 Phase 1

New character: Chasca
![Screenshot From 2024-11-23 18-38-12](https://github.com/user-attachments/assets/efd73090-3d30-475a-b37b-9be49db12d26)
![Screenshot From 2024-11-23 18-38-36](https://github.com/user-attachments/assets/e4cf25ea-00f7-4254-ac3f-1aee7c27e9fe)

**Note**: The character information like ATK, DEF and HP are yet to be updated as these values are still not available Genshin Impact Wiki. Also, test cases will added once all the information is available.

Fixes: #221

2024-11-24 16:04 UTC, sdglitched commented
Data is now updated in Genshin Wiki. :rocket: 

- Chasca
![Screenshot From 2024-11-24 20-58-07](https://github.com/user-attachments/assets/8ac209c8-927f-4208-abd4-f997fd9e292e)
![Screenshot From 2024-11-24 20-47-35](https://github.com/user-attachments/assets/d23ac9d5-c0d4-4ca9-8332-71531449299b)

- Ororon
![Screenshot From 2024-11-24 20-57-56](https://github.com/user-attachments/assets/1cfe9cfc-f72a-463d-b8fd-72876db7cdc0)
![Screenshot From 2024-11-24 20-55-30](https://github.com/user-attachments/assets/2066118c-2a62-4a66-a0a2-83bd084cf927)

Test Coverage
![Screenshot From 2024-11-24 21-12-11](https://github.com/user-attachments/assets/7c88bce2-3151-4ba4-8d63-b421a30eb8f6)

2024-11-25 06:56 UTC, gridhead requested changes
Apart from Chasca's constellation, this looks good to me.

2024-11-25 06:56 UTC, gridhead commented on assets/cons.qrc
Could you please add the constellation details for the Chasca?

2024-11-26 03:03 UTC, gridhead approved these changes
I am going ahead with the merge but this needs following up.

Related issue ticket. #227

2024-11-26 03:03 UTC, merged